from django.db import models

class SquirrelDetail(models.Model):
    X = models.DecimalField(decimal_places=100,max_digits=100)
    Y = models.DecimalField(decimal_places=100,max_digits=100)
    Unique_Squirrel_ID = models.CharField(max_length=100)
    Hectare = models.CharField(max_length=100)
    Shift = models.CharField(max_length=2)
    Date = models.DateField()
    Hectare_Squirrel_Number = models.IntegerField()
    Age = models.CharField(max_length=30)
    Primary_Fur_Color = models.CharField(max_length=50)
    Highlight_Fur_Color = models.CharField(max_length=100)
    Combination_of_Primary_and_Highlight_Color = models.CharField(max_length=100)
    Color_notes = models.CharField(max_length=100)
    Location = models.CharField(max_length=100)
    Above_Ground_Sighter_Measurement = models.CharField(max_length=100)
    Specific_Location = models.CharField(max_length=100)
    Running = models.BooleanField()
    Chasing = models.BooleanField()
    Climbing = models.BooleanField()
    Eating = models.BooleanField()
    Foraging = models.BooleanField()
    Other_Activities = models.CharField(max_length=100)
    Kuks = models.BooleanField()
    Quaas = models.BooleanField()
    Moans = models.BooleanField()
    Tail_flags = models.BooleanField()
    Tail_twitches = models.BooleanField()
    Approaches = models.BooleanField()
    Indifferent = models.BooleanField()
    Runs_from = models.BooleanField()
    Other_Interactions = models.CharField(max_length=100)
    Lat_Long = models.CharField(max_length=100)
