# Generated by Django 3.1.2 on 2020-10-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201015_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Approaches',
            new_name='approaches',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Chasing',
            new_name='chasing',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Climbing',
            new_name='climbing',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Eating',
            new_name='eating',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Foraging',
            new_name='foraging',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Indifferent',
            new_name='indifferent',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Kuks',
            new_name='kuks',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Moans',
            new_name='moans',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Other_Activities',
            new_name='other_activities',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Primary_Fur_Color',
            new_name='primary_fur_color',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Quaas',
            new_name='quaas',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Running',
            new_name='running',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Runs_from',
            new_name='runs_from',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Specific_Location',
            new_name='specific_location',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Tail_flags',
            new_name='tail_flags',
        ),
        migrations.RenameField(
            model_name='squirreldetail',
            old_name='Tail_twitches',
            new_name='tail_twitches',
        ),
    ]
