# Generated by Django 3.1.2 on 2020-10-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20201015_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirreldetail',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='unique_squirrel_id',
            field=models.CharField(help_text='Unique squirrel id of squirrel', max_length=14, primary_key=True, serialize=False),
        ),
    ]
