# Generated by Django 3.1.2 on 2020-10-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20201016_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetail',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='approaches',
            field=models.BooleanField(help_text='Approaches'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='chasing',
            field=models.BooleanField(help_text='Is the squirrel chasing?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='climbing',
            field=models.BooleanField(help_text='Is the squirrel climbing?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='eating',
            field=models.BooleanField(help_text='Is the squirrel eating?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='foraging',
            field=models.BooleanField(help_text='Is the squirrel foraging?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='indifferent',
            field=models.BooleanField(help_text='Indifferent'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='kuks',
            field=models.BooleanField(help_text='The squirrel kuks?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='moans',
            field=models.BooleanField(help_text='The squirrel moans?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='primary_fur_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='quaas',
            field=models.BooleanField(help_text='The squirrel quaas?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='running',
            field=models.BooleanField(help_text='Is the squirrel running?'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='runs_from',
            field=models.BooleanField(help_text='Runs_from'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='specific_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='tail_flags',
            field=models.BooleanField(help_text='Tail flags'),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='tail_twitches',
            field=models.BooleanField(help_text='Tail twitches'),
        ),
    ]
