# Generated by Django 3.1.2 on 2020-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_auto_20201016_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetail',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age of squirrel', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='other_activities',
            field=models.CharField(help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='primary_fur_color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='squirreldetail',
            name='specific_location',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
